package pages

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/italiatroller-1990/garterscopic/internal/config"
	"github.com/italiatroller-1990/garterscopic/internal/routing"
	"github.com/italiatroller-1990/garterscopic/internal/yaml"
)

type Page struct {
	SourcePath string
	Route      string
	Type       string
	Metadata   map[string]any
	Body       string
	RawContent string

	Section       string
	Tags          []string
	Categories    []string
	Date          string
	Draft         bool
	Slug          string
	AutoGenerated bool
	AutoLayout    string
	AutoPageType  string

	// SEO fields
	Title       string
	Description string
	Keywords    string
	Canonical   string
	Robots      string
	OGTitle     string
	OGDesc      string
	OGImage     string
}

const frontmatterDelim = "---"

func ParsePages(cfg *config.SiteConfig) ([]Page, error) {
	pagesDir := cfg.SourcePath("pages")

	var pages []Page

	if err := filepath.Walk(pagesDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		if filepath.Ext(path) != ".md" {
			return nil
		}

		relPath, err := filepath.Rel(pagesDir, path)
		if err != nil {
			return err
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read page %s: %w", path, err)
		}

		page, err := parsePage(string(data), path, relPath)
		if err != nil {
			return fmt.Errorf("failed to parse page %s: %w", path, err)
		}

		if page.Type == "" {
			page.Type = cfg.DefaultPageType
		}

		if page.Slug == "" {
			page.Slug = deriveSlug(relPath)
		}

		// Extract SEO fields from frontmatter
		page.Title = extractString(page.Metadata, "title")
		page.Description = extractString(page.Metadata, "description")
		page.Keywords = extractString(page.Metadata, "keywords")
		page.Canonical = extractString(page.Metadata, "canonical")
		page.Robots = extractString(page.Metadata, "robots")
		page.OGTitle = extractString(page.Metadata, "og_title")
		page.OGDesc = extractString(page.Metadata, "og_description")
		page.OGImage = extractString(page.Metadata, "og_image")

		pages = append(pages, page)
		return nil
	}); err != nil {
		return nil, err
	}

	for i := range pages {
		pages[i].Route = routing.GenerateRoute(pages[i].SourcePath, cfg.SourcePath("pages"))
	}

	return pages, nil
}

func ParsePosts(cfg *config.SiteConfig) ([]Page, error) {
	postsDir := cfg.SourcePath("posts")

	if _, err := os.Stat(postsDir); os.IsNotExist(err) {
		return nil, nil
	}

	var posts []Page

	if err := filepath.Walk(postsDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		if filepath.Ext(path) != ".md" {
			return nil
		}

		relPath, err := filepath.Rel(postsDir, path)
		if err != nil {
			return err
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read post %s: %w", path, err)
		}

		page, err := parsePage(string(data), path, relPath)
		if err != nil {
			return fmt.Errorf("failed to parse post %s: %w", path, err)
		}

		if page.Type == "" {
			page.Type = "post"
		}

		section := detectSection(relPath)
		page.Section = section

		page.Tags = extractTags(page.Metadata)
		page.Categories = extractStringList(page.Metadata, "categories")
		page.Date = extractDate(page.Metadata)
		page.Draft = extractDraft(page.Metadata)

		if page.Slug == "" {
			page.Slug = deriveSlug(relPath)
		}

		// Extract SEO fields from frontmatter
		page.Title = extractString(page.Metadata, "title")
		page.Description = extractString(page.Metadata, "description")
		page.Keywords = extractString(page.Metadata, "keywords")
		page.Canonical = extractString(page.Metadata, "canonical")
		page.Robots = extractString(page.Metadata, "robots")
		page.OGTitle = extractString(page.Metadata, "og_title")
		page.OGDesc = extractString(page.Metadata, "og_description")
		page.OGImage = extractString(page.Metadata, "og_image")

		posts = append(posts, page)
		return nil
	}); err != nil {
		return nil, err
	}

	for i := range posts {
		posts[i].Route = generatePostRoute(posts[i].Section, posts[i].SourcePath, postsDir)
	}

	sort.Slice(posts, func(i, j int) bool {
		return posts[i].Date > posts[j].Date
	})

	return posts, nil
}

func detectSection(relPath string) string {
	parts := strings.Split(filepath.ToSlash(relPath), "/")
	if len(parts) > 1 {
		return parts[0]
	}
	return ""
}

func extractTags(metadata map[string]any) []string {
	return extractStringList(metadata, "tags")
}

func extractStringList(metadata map[string]any, key string) []string {
	listVal, ok := metadata[key]
	if !ok {
		return nil
	}

	list, ok := listVal.([]any)
	if !ok {
		return nil
	}

	var result []string
	for _, item := range list {
		if s, ok := item.(string); ok && s != "" {
			result = append(result, s)
		}
	}
	sort.Strings(result)
	return result
}

func extractDate(metadata map[string]any) string {
	if dateVal, ok := metadata["date"]; ok {
		switch v := dateVal.(type) {
		case string:
			return v
		case time.Time:
			return v.Format("2006-01-02")
		}
	}
	return ""
}

func extractDraft(metadata map[string]any) bool {
	if draftVal, ok := metadata["draft"]; ok {
		if b, ok := draftVal.(bool); ok {
			return b
		}
	}
	return false
}

func extractString(metadata map[string]any, key string) string {
	if val, ok := metadata[key]; ok {
		if s, ok := val.(string); ok {
			return s
		}
	}
	return ""
}

func deriveSlug(relPath string) string {
	name := strings.TrimSuffix(filepath.Base(relPath), ".md")
	return name
}

func generatePostRoute(section, sourcePath, postsDir string) string {
	relPath, err := filepath.Rel(postsDir, sourcePath)
	if err != nil {
		return "/"
	}

	relPath = strings.TrimSuffix(relPath, ".md")
	parts := strings.Split(filepath.ToSlash(relPath), "/")

	if section != "" && len(parts) > 1 {
		parts = parts[1:]
	}

	var routeParts []string
	for _, part := range parts {
		if part == "" || part == "index" {
			continue
		}
		routeParts = append(routeParts, part)
	}

	if len(routeParts) == 0 {
		if section != "" {
			return "/" + section + "/"
		}
		return "/"
	}

	if section != "" {
		return "/" + section + "/" + strings.Join(routeParts, "/") + "/"
	}

	return "/" + strings.Join(routeParts, "/") + "/"
}

func Sections(posts []Page) []string {
	seen := make(map[string]bool)
	var sections []string

	for _, p := range posts {
		if p.Section != "" && !seen[p.Section] {
			seen[p.Section] = true
			sections = append(sections, p.Section)
		}
	}

	sort.Strings(sections)
	return sections
}

func PostsBySection(posts []Page, section string) []Page {
	var result []Page
	for _, p := range posts {
		if p.Section == section {
			result = append(result, p)
		}
	}
	return result
}

func PostsByTag(posts []Page, tag string) []Page {
	return PostsByListValue(posts, tag, func(p Page) []string { return p.Tags })
}

func PostsByCategory(posts []Page, category string) []Page {
	return PostsByListValue(posts, category, func(p Page) []string { return p.Categories })
}

func PostsByListValue(posts []Page, value string, extract func(Page) []string) []Page {
	var result []Page
	for _, p := range posts {
		for _, v := range extract(p) {
			if v == value {
				result = append(result, p)
				break
			}
		}
	}
	return result
}

func AllTags(posts []Page) []string {
	return AllListValues(posts, func(p Page) []string { return p.Tags })
}

func AllCategories(posts []Page) []string {
	return AllListValues(posts, func(p Page) []string { return p.Categories })
}

func AllListValues(posts []Page, extract func(Page) []string) []string {
	seen := make(map[string]bool)
	var values []string

	for _, p := range posts {
		for _, v := range extract(p) {
			if !seen[v] {
				seen[v] = true
				values = append(values, v)
			}
		}
	}

	sort.Strings(values)
	return values
}

func TagIndex(posts []Page) map[string][]Page {
	return ListIndex(posts, func(p Page) []string { return p.Tags })
}

func CategoryIndex(posts []Page) map[string][]Page {
	return ListIndex(posts, func(p Page) []string { return p.Categories })
}

func ListIndex(posts []Page, extract func(Page) []string) map[string][]Page {
	index := make(map[string][]Page)
	for _, p := range posts {
		for _, v := range extract(p) {
			index[v] = append(index[v], p)
		}
	}
	return index
}

func parsePage(content string, sourcePath, relPath string) (Page, error) {
	page := Page{
		SourcePath: sourcePath,
	}

	if !strings.HasPrefix(content, frontmatterDelim) {
		page.Body = content
		page.Metadata = make(map[string]any)
		return page, nil
	}

	lines := strings.Split(content, "\n")
	endIdx := -1

	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == frontmatterDelim {
			endIdx = i
			break
		}
	}

	if endIdx == -1 {
		page.Body = content
		page.Metadata = make(map[string]any)
		return page, nil
	}

	frontmatter := strings.Join(lines[1:endIdx], "\n")
	if err := yaml.Parse([]byte(frontmatter), &page.Metadata); err != nil {
		return Page{}, fmt.Errorf("invalid frontmatter: %w", err)
	}

	bodyLines := lines[endIdx+1:]
	if len(bodyLines) > 0 && bodyLines[0] == "" {
		bodyLines = bodyLines[1:]
	}
	page.Body = strings.Join(bodyLines, "\n")
	page.RawContent = page.Body

	if pageType, ok := page.Metadata["type"].(string); ok {
		page.Type = pageType
	}

	return page, nil
}

func (p *Page) RelativePath(baseDir string) string {
	rel, _ := filepath.Rel(baseDir, p.SourcePath)
	return rel
}
